"""creat posts table

Revision ID: aba6c4bb63a8
Revises: dd1a3700e086
Create Date: 2023-03-11 15:15:03.542860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba6c4bb63a8'
down_revision = 'dd1a3700e086'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('posts', 'catagory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('catagory', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
